name: Build LaTeX Documents
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          tex-distribution: texlive-full

      - name: Compile Russian CV
        run: |
          cd src
          pdflatex -interaction=nonstopmode cv_ru.tex
          mv cv_ru.pdf ..
          
      - name: Compile English CV
        run: |
          cd src
          pdflatex -interaction=nonstopmode cv_en.tex
          mv cv_en.pdf ..
          
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: |
            cv_ru.pdf
            cv_en.pdf
