name: Build and Release CV
on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Необходимо для создания релизов

    steps:
      # Шаг 1: Загрузка репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка TeX Live
      - name: Setup TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          scheme: full
          os: debian
          run: |
            apt-get update -y
            apt-get install -y texlive-full

      # Шаг 3: Компиляция документов
      - name: Compile Russian CV
        run: |
          cd ./src
          pdflatex -interaction=nonstopmode cv_rus.tex
          mv cv_rus.pdf ..
          
      - name: Compile English CV
        run: |
          cd ./src
          pdflatex -interaction=nonstopmode cv_eng.tex
          mv cv_eng.pdf ..

      # Шаг 4: Создание релиза и прикрепление PDF
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: |
            cv_rus.pdf
            cv_eng.pdf
          generate_release_notes: true
          draft: false

      # Шаг 5: Загрузка артефактов (для обычных push)
      - name: Upload Artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            cv_rus.pdf
            cv_eng.pdf
