name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Компиляция каждого файла отдельно
      - name: Compile Russian CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/cv_ru.tex
          working_directory: src/

      - name: Compile English CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/cv_en.tex
          working_directory: src/

      - name: Move PDF files
        run: |
          mv src/cv_ru.pdf .
          mv src/cv_en.pdf .

      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            cv_ru.pdf
            cv_en.pdf
