
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          scheme: full
          os: debian
          run: |
            apt-get update -y
            apt-get install -y texlive-full
            pdflatex ./src/cv_rus.tex
            pdflatex ./src/cv_eng.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            cv_rus.pdf
            cv_eng.pdf
