
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v3
        with:
          run: |
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode ./src/cv_rus.tex
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode ./src/cv_eng.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            cv_rus.pdf
            cv_eng.pdf
