name: Build and Release CurriculumVitae
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TeX Live
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-pictures \
            texlive-bibtex-extra \
            texlive-lang-cyrillic \
            texlive-plain-generic \
            cm-super

      - name: Compile RUS
        working-directory: src
        run: pdflatex -interaction=nonstopmode cv_rus.tex

      - name: Compile ENG
        working-directory: src
        run: pdflatex -interaction=nonstopmode cv_eng.tex

      # Выгрузка результатов:
      - name: Upload RUS
        uses: actions/upload-artifact@v4
        with:
          name: cv_rus
          path: src/cv_rus.pdf
      - name: Upload ENG
        uses: actions/upload-artifact@v4
        with:
          name: cv_eng
          path: src/cv_eng.pdf
      - name: Upload Both
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: |
            src/cv_rus.pdf
            src/cv_eng.pdf

      # - name: Check for document changes
      #   id: changes
      #   run: |
      #     if git rev-parse latest^{commit} >/dev/null 2>&1; then
      #       TAG_COMMIT=$(git rev-parse latest^{commit})
      #       if git diff --name-only "$TAG_COMMIT" HEAD | grep -qE '\.(tex|bib|jpg|png|svg|eps|cls|sty)$'; then
      #         echo "should_release=true" >> $GITHUB_OUTPUT
      #       else
      #         echo "should_release=false" >> $GITHUB_OUTPUT
      #       fi
      #     else
      #       echo "should_release=true" >> $GITHUB_OUTPUT
      #     fi

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest CV
          make_latest: true
          files: |
            src/cv_rus.pdf
            src/cv_eng.pdf
