name: Build and Release CV
on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Необходимо для создания релизов

    steps:
      # Шаг 1: Загрузка репозитория:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка TeX Live и компиляция документов:
      - name: Setup TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          scheme: full
          os: debian
          run: |
            apt-get update -y
            apt-get install -y texlive-full
            cd ./src
            pdflatex -interaction=nonstopmode cv_rus.tex
            pdflatex -interaction=nonstopmode cv_eng.tex

      # Шаг 3: Создание релиза и прикрепление PDF:
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: |
            src/cv_rus.pdf
            src/cv_eng.pdf
          generate_release_notes: true
          draft: false

      # Шаг 4: Загрузка артефактов (для обычных push):
      - name: Upload Artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            src/cv_rus.pdf
            src/cv_eng.pdf
