name: Build and Release CV
on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Необходимо для создания релизов

    steps:

      # Debag:
      - name: Debug event type
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Ref: ${{ github.ref }}"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем всю историю для работы с тегами

      # Шаг 1: Загрузка репозитория:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка TeX Live и компиляция документов:
      - name: Setup TeX Live
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          scheme: full
          os: debian
          run: |
            apt-get update -y
            apt-get install -y texlive-full
            cd ./src
            pdflatex -interaction=nonstopmode cv_rus.tex
            pdflatex -interaction=nonstopmode cv_eng.tex
            mv *.pdf ..

      # Debag:
      - name: List files before release
        run: ls -la

      # Шаг 3: Создание релиза и прикрепление PDF:
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: |
            cv_rus.pdf
            cv_eng.pdf
          generate_release_notes: true
          draft: false
        # Debug:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debug:
      - name: Check if release step was skipped
        if: ${{ github.event_name == 'release' && !steps.create_release.outputs.id }}
        run: |
          echo "Release step was skipped or failed!"
          echo "Check permissions and workflow configuration"

      # Шаг 4: Загрузка артефактов (для обычных push):
      - name: Upload Artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            cv_rus.pdf
            cv_eng.pdf
