name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ./src/cv_rus.tex
            ./src/cv_eng.tex
          args: -jobname=my_doc -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          compiler: latexmk

      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            cv_rus.pdf
            cv_eng.pdf
