name: Build LaTeX Documents

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup TeX Live
        uses: dante-ev/latex-action@v3
        with:
          tex-distribution: texlive-full
        
      - name: Compile Russian CurriculumVitae
        run: |
          cd CurriculumVitae/src
          pdflatex -interaction=nonstopmode cv_ru.tex
          mv cv_ru.pdf ..
        
      - name: Compile English CurriculumVitae
        run: |
          cd CurriculumVitae/src
          pdflatex -interaction=nonstopmode cv_en.tex
          mv cv_en.pdf ..
          
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CurriculumVitae/cv_ru.pdf
            CurriculumVitae/cv_en.pdf
