name: Build and Release CurriculumVitae
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      # Компиляция:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: latest
          scheme: full
          os: debian
          run: |
            apt-get update -y
            apt-get install -y texlive-full
            cd ./src
            pdflatex cv_rus.tex
            pdflatex cv_eng.tex
            mv *.tex ..

      # Выгрузка результатов:
      - name: Upload RUS
        uses: actions/upload-artifact@v4
        with:
          name: cv_rus
          path: cv_rus.pdf
      - name: Upload ENG
        uses: actions/upload-artifact@v4
        with:
          name: cv_eng
          path: cv_eng.pdf
      - name: Upload Both
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: |
            cv_rus.pdf
            cv_eng.pdf
